# Generated by Django 5.1 on 2024-08-23 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='codigo',
            field=models.CharField(max_length=6, primary_key=True, serialize=False, unique=True),
        ),
    ]
